
trigger:
- none

pr: none
pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: HPA_VPA_in_AKS
  displayName: HPA_VPA_in_AKS
  jobs:
  - deployment: HPA_VPA_in_AKS
    displayName: HPA_VPA_in_AKS
    environment: "dev"
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'Azure DevOps Service Connection'
              azureResourceGroup: 'bankapp-rg'
              kubernetesCluster: 'bankapp-cluster'
              namespace: '*'
              manifests: 'hpa-vpa/*'
