
trigger:
- none

pr: none
pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: CronJobSnapshot
  displayName: CronJobSnapshot
  jobs:
  - deployment: CronJobSnapshot
    displayName: CronJobSnapshot
    environment: "prod"
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: CmdLine@2
            inputs:
              script: 'sed -i -e ''s/#{VAULT_TOKEN}#/$(VAULT_TOKEN)/g'' snapshot-restore/job-for-vault-restore.yaml'
          - task: CmdLine@2
            inputs:
              script: 'sed -i -e ''s@#{SAS_TOKEN_RESTORE}#@$(SAS_TOKEN_RESTORE)@g'' snapshot-restore/job-for-vault-restore.yaml'
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'Azure DevOps Service Connection'
              azureResourceGroup: 'bankappprod-rg'
              kubernetesCluster: 'bankappprod-cluster'
              namespace: 'default'
              manifests: 'snapshot-restore/*'
