# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: ClusterIP
  clusterIP: None # Headless service for stable pod DNS
  ports:
  - port: 3306
    name: mysql
  selector:
    app: mysql
    release: my-mysql-release # Replace with your release name

# statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
    release: my-mysql-release # Replace with your release name
spec:
  serviceName: mysql-service
  replicas: 2 # Primary and secondary pods
  selector:
    matchLabels:
      app: mysql
      release: my-mysql-release
  template:
    metadata:
      labels:
        app: mysql
        release: my-mysql-release
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: your_root_password
          - name: MYSQL_DATABASE
            value: your_database_name
          - name: MYSQL_USER
            value: your_user_name
          - name: MYSQL_PASSWORD
            value: your_user_password
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
      - ReadWriteOnce # Only one pod at a time can mount this volume
      resources:
        requests:
          storage: 1Gi # Adjust storage size as needed
      storageClassName: gp2 #  Specify your EBS storage class
